/ const menuData = {
//   Café: [
//     {
//       nombre: "Ristretto",
//       descripcion: "Café corto",
//       tamaño: "25ml",
//       precio: 2500,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Espresso",
//       descripcion: "Café fuerte",
//       tamaño: "40ml",
//       precio: 2.5,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Lungo",
//       descripcion: "Café largo",
//       tamaño: "110ml",
//       precio: 3.0,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Latte",
//       descripcion: "Café con leche",
//       tamaño: "110ml",
//       precio: 3.5,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Lágrima",
//       descripcion: "Un toque de café con mucha leche",
//       tamaño: "200ml",
//       precio: 3.0,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Cortado",
//       descripcion: "Café con poca leche",
//       tamaño: "150ml",
//       precio: 3.0,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Café con leche",
//       descripcion: "Mezcla clásica de café con leche",
//       tamaño: "200ml",
//       precio: 3.5,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Café Benita",
//       descripcion: "Café con licor",
//       tamaño: "200ml",
//       precio: 4.0,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Café Helado",
//       descripcion: "Café frío",
//       tamaño: "300ml",
//       precio: 4.0,
//       imagen: "/api/placeholder/300/200",
//     },
//   ],
//   "Sin Café": [
//     {
//       nombre: "Submarino",
//       descripcion: "Leche caliente con barra de chocolate",
//       tamaño: "250ml",
//       precio: 4.5,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Chocolatada",
//       descripcion: "Leche con chocolate",
//       tamaño: "250ml",
//       precio: 4.0,
//       imagen: "/api/placeholder/300/200",
//     },
//   ],
//   Té: [
//     {
//       nombre: "Té",
//       descripcion: "Té clásico",
//       tamaño: "200ml",
//       precio: 2.0,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Té con leche",
//       descripcion: "Té con leche",
//       tamaño: "200ml",
//       precio: 2.5,
//       imagen: "/api/placeholder/300/200",
//     },
//   ],
//   Alfajores: [
//     {
//       nombre: "Blanco / Negro",
//       descripcion: "Alfajor clásico de chocolate",
//       tamaño: "individual",
//       precio: 1.5,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Conito Dulce de Leche",
//       descripcion: "Cono relleno de dulce de leche",
//       tamaño: "individual",
//       precio: 2.0,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Galletas bañadas en chocolate",
//       descripcion: "Galletas cubiertas de chocolate",
//       tamaño: "paquete",
//       precio: 1.5,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Galletas con Arándanos",
//       descripcion: "Galletas con trozos de arándanos",
//       tamaño: "paquete",
//       precio: 1.75,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Galletas con Chips de Chocolate",
//       descripcion: "Galletas con chips de chocolate",
//       tamaño: "paquete",
//       precio: 1.75,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Bombon Frutal",
//       descripcion: "Bombón relleno de frutas",
//       tamaño: "individual",
//       precio: 2.0,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Estuche x 2 alfajores",
//       descripcion: "Caja con dos alfajores",
//       tamaño: "estuche",
//       precio: 3.5,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Estuche Triologia 6 alfajores",
//       descripcion: "Caja con seis alfajores",
//       tamaño: "estuche",
//       precio: 9.0,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Cordobés",
//       descripcion: "Alfajor típico de Córdoba",
//       tamaño: "individual",
//       precio: 2.0,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "de Cacao",
//       descripcion: "Alfajor de cacao",
//       tamaño: "individual",
//       precio: 1.75,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "de Coco",
//       descripcion: "Alfajor de coco",
//       tamaño: "individual",
//       precio: 1.75,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "de Merengue",
//       descripcion: "Alfajor cubierto de merengue",
//       tamaño: "individual",
//       precio: 1.75,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "de Maicena",
//       descripcion: "Alfajor de maicena",
//       tamaño: "individual",
//       precio: 1.5,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Conito de Dulce de Leche",
//       descripcion: "Conito relleno de dulce de leche",
//       tamaño: "individual",
//       precio: 2.0,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Colacion",
//       descripcion: "Alfajor típico",
//       tamaño: "individual",
//       precio: 1.5,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Nuez Confitada",
//       descripcion: "Alfajor con nueces confitadas",
//       tamaño: "individual",
//       precio: 2.25,
//       imagen: "/api/placeholder/300/200",
//     },
//   ],
//   "Dulces Caseros": [
//     {
//       nombre: "Cookies vainilla con chips",
//       descripcion: "Galletas de vainilla con chips",
//       tamaño: "paquete",
//       precio: 2.0,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Cookies chocolate con nuez",
//       descripcion: "Galletas de chocolate y nuez",
//       tamaño: "paquete",
//       precio: 2.25,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Palmeritas",
//       descripcion: "Palmeritas de hojaldre",
//       tamaño: "paquete",
//       precio: 1.75,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Alfajorcitos de Maicena",
//       descripcion: "Pequeños alfajores de maicena",
//       tamaño: "individual",
//       precio: 2.0,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Medialunas",
//       descripcion: "Medialunas dulces",
//       tamaño: "unidad",
//       precio: 1.5,
//       imagen: "/api/placeholder/300/200",
//     },
//     {
//       nombre: "Criollos",
//       descripcion: "Criollos salados",
//       tamaño: "unidad",
//       precio: 1.5,
//       imagen: "/api/placeholder/300/200",
//     },
//   ],
// };