<?php
$fortunes = [
	"La fortuna favorece a los valientes.",
	"Un viaje de mil millas comienza con un solo paso.",
	"La paciencia es amarga, pero sus frutos son dulces.",
	"La mejor manera de predecir el futuro es crearlo.",
	"La vida es lo que pasa mientras estás ocupado haciendo otros planes.",
	"El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
	"La creatividad es la inteligencia divirtiéndose.",
	"Nunca es tarde para ser lo que podrías haber sido.",
	"El optimismo es la fe que conduce al logro.",
	"La felicidad no es algo hecho. Viene de tus propias acciones.",
	"La vida es un misterio que se revela a sí mismo.",
	"La verdadera sabiduría está en reconocer lo que no sabemos.",
	"La felicidad no es una estación a la que llegas, sino un modo de viajar.",
	"El pasado es historia, el futuro es un misterio, el presente es un regalo.",
	"La vida es lo que hacemos de ella.",
	"El universo está lleno de magia, solo tienes que creer en ella.",
	"La paz comienza con una sonrisa.",
	"La gratitud es la memoria del corazón.",
	"La felicidad es el resultado de estar satisfechos con uno mismo.",
	"La vida es un sueño, así que vívela al máximo.",
	"El único lugar donde el éxito viene antes del trabajo es en el diccionario.",
	"La vida es un viaje, disfruta el viaje.",
	"La vida es corta, sonríe mientras todavía tienes dientes.",
	"La vida es un regalo, nunca dejes de creer en ti mismo.",
	"La vida es un viaje, disfruta el viaje.",
	"Sigue tus sueños.",
	"Cree en ti mismo",
	"La felicidad está en las pequeñas cosas.",
	"El cambio es la única constante en la vida.",
	"La verdadera felicidad viene de dentro.",
	"Aprende de tus errores.",
	"La suerte está de tu lado.",
	"El tiempo cura todas las heridas.",
	"Los sueños se hacen realidad.",
	"Un nuevo amigo es un tesoro.",
	"La felicidad y el bien consisten en hacer lo que es propio de un ser humano - Marco Aurelio.",
	"No es a la muerte a lo que el hombre debe temer, sino a no empezar a vivir - Marco Aurelio.",
	"La virtud es lo único bueno, y el vicio lo único malo - Epicteto ",
	"La felicidad no es algo hecho. Viene de tus propias acciones - Aristóteles  ",
	"No pretendas que los acontecimientos ocurran como tú deseas; desea, más bien, que sucedan como suceden y serás feliz - Marco Aurelio.",
	"Las cosas de las que huyes están dentro de ti - Marco Aurelio.",
	"El hombre conquista el mundo al conquistarse a sí mismo -  Zenón de Citio",
	"Todo lo que escuchamos es solo una opinión, no un hecho. Lo que vemos es una perspectiva, no la realidad - Marco Aurelio.",
	"Vive como si fueras a morir mañana. Aprende como si fueras a vivir siempre - Mahatma Gandhi.",
	"La vida es lo que hacemos de ella - Marco Aurelio.",
	"Si no conviene, no lo hagas; si no es verdad, no lo digas - Marco Aurelio.",
	"La verdad triunfa por sí misma, la mentira necesita siempre complicidad - Epicteto.",
	"La vida es un sueño, así que vívela al máximo.",
	"La felicidad no es una estación a la que llegas, sino un modo de viajar.",
	"Si no puedes encontrar la solución, busca una nueva pregunta.",
	"El futuro es incierto, pero tu peinado está increíble",
	"La vida es una caja de chocolates... ¡Y a veces te toca el relleno!",
	"La gratitud es la memoria del corazón.",


];

return $fortunes[array_rand($fortunes)];
